.PHONY: clean All

All:
	@echo "----------Building project:[ baitap - Debug ]----------"
	@cd "baitap" && "$(MAKE)" -f  "baitap.mk"
clean:
	@echo "----------Cleaning project:[ baitap - Debug ]----------"
	@cd "baitap" && "$(MAKE)" -f  "baitap.mk" clean
